# Generated by Django 5.1 on 2024-09-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
